### ISSUE TITLE
 installation problem grblweb raspberry pi 3

### ISSUE THREAD

**Issue by Hoangthoi** [andrewhodel/grblweb#27]

**Comment by andrewhodel** [comment]
I would recommend spending some time and learning computer programming, if
you plan on running a CNC.  I am sorry to break it to you but it looks like
you don't have any idea on how to run that application.

It's not like you are connecting to a wifi network or something simple like
that.

You could probably also pay someone to teach you or set it up, like
consulting.

I built the application for myself, and I shared it so people who know how
to figure it out can use it.  I didn't make it difficult but there's a
basic set of understanding that needs to be understood to use that kind of
stuff.  Take a look at Millcrum.com for example, it's the same way.

I would have tried to sell it, but as soon as I got it to a working point
there was already a few million dollars in revenue from companies using
that code.  I don't know why they didn't just contact me to work with me.

I don't think it's "made easy" by having to build a machine, learn stepper
motors, put together an AVR, solder everything together so it doesn't
vibrate apart and figure out all the cut rates (that are in books) because
it takes probably 6 months of hard work.  Then you have to learn all the
software too.  Hell, there's people making 100 million a year doing
nothing, they could just buy a HAAS with a FANUC controller and they'd be
at the same point.  Except they would have made that money in about 20
minutes.  Hopefully the money has set things up where previous skills
learned are equal to compensation.

I don't think there's anything wrong with that, I do think it's hard to
find someone to teach you one on one but dude there is so much
documentation on how to learn programming.  It is just a complicated
subject.

The best advice I can give you would be learn what you are typing and what
it is doing rather than just copy and paste.



Andrew

**Comment by Hoangthoi** [comment]
I'm sorry, I'm not good at English, so I use google translate, in the sentence may be wrong. I have a spare raspberry pi 3, I want to try running grblweb, I do the installation way but it does not run.

**Comment by ejs-ejs** [comment]
Hi Andrew,
maybe a DRO patch for GRBL 1.1 might calm you ?
:)
